# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    env(DATABASE_HOST): '127.0.0.1'
    env(DATABASE_NAME): 'php_course'
    env(DATABASE_USER): 'x3r1x'
    env(DATABASE_PASSWORD): '1234'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    PDO:
        class: PDO
        arguments:
            - "mysql:host=%env(DATABASE_HOST)%;dbname=%env(DATABASE_NAME)%;charset=utf8mb4"
            - "%env(DATABASE_USER)%"
            - "%env(DATABASE_PASSWORD)%"

        calls:
            - [ "setAttribute", [ !php/const PDO::ATTR_ERRMODE, !php/const PDO::ERRMODE_EXCEPTION ] ]
            - [ "setAttribute", [ !php/const PDO::ATTR_DEFAULT_FETCH_MODE, !php/const PDO::FETCH_ASSOC ] ]

    App\User\Model\UserTable:
    # autowire: true
    #    arguments:
    #        - '@PDO'
